export const USER_OTP_GENERATE_REQUEST = "USER_OTP_GENERATE_REQUEST";
export const USER_OTP_GENERATE_SUCCESS = "USER_OTP_GENERATE_SUCCESS";
export const USER_OTP_GENERATE_FAIL = "USER_OTP_GENERATE_FAIL";
export const USER_OTP_GENERATE_RESET = "USER_OTP_GENERATE_RESET";

export const USER_VERIFY_OTP_REQUEST = "USER_VERIFY_OTP_REQUEST";
export const USER_VERIFY_OTP_SUCCESS = "USER_VERIFY_OTP_SUCCESS";
export const USER_VERIFY_OTP_FAIL = "USER_VERIFY_OTP_FAIL";
export const USER_VERIFY_OTP_RESET = "USER_VERIFY_OTP_RESET";

export const USER_CREATE_PIN_REQUEST = "USER_CREATE_PIN_REQUEST";
export const USER_CREATE_PIN_SUCCESS = "USER_CREATE_PIN_SUCCESS";
export const USER_CREATE_PIN_FAIL = "USER_CREATE_PIN_FAIL";
export const USER_CREATE_PIN_RESET = "USER_CREATE_PIN_RESET";

export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";
export const USER_LOGIN_RESET = "USER_LOGIN_RESET";

export const USER_PIN_RESET_REQUEST = "USER_PIN_RESET_REQUEST";
export const USER_PIN_RESET_SUCCESS = "USER_PIN_RESET_SUCCESS";
export const USER_PIN_RESET_FAIL = "USER_PIN_RESET_FAIL";
export const USER_PIN_RESET_RESET = "USER_PIN_RESET_RESET";


export const USER_PIN_CHANGE_REQUEST = "USER_PIN_CHANGE_REQUEST";
export const USER_PIN_CHANGE_SUCCESS = "USER_PIN_CHANGE_SUCCESS";
export const USER_PIN_CHANGE_FAIL = "USER_PIN_CHANGE_FAIL";

export const USER_LOGOUT_REQUEST = "USER_LOGOUT_REQUEST";
export const USER_LOGOUT_SUCCESS = "USER_LOGOUT_SUCCESS";


