export const CREATE_BUSINESS_REQUEST = "CREATE_BUSINESS_REQUEST";
export const CREATE_BUSINESS_SUCCESS = "CREATE_BUSINESS_SUCCESS";
export const CREATE_BUSINESS_FAIL = "CREATE_BUSINESS_FAIL";
export const CREATE_BUSINESS_RESET = "CREATE_BUSINESS_RESET";

export const GET_ALL_BUSINESS_REQUEST = "GET_ALL_BUSINESS_REQUEST";
export const GET_ALL_BUSINESS_SUCCESS = "GET_ALL_BUSINESS_SUCCESS";
export const GET_ALL_BUSINESS_FAIL = "GET_ALL_BUSINESS_FAIL";
export const GET_ALL_BUSINESS_RESET = "GET_ALL_BUSINESS_RESET";

export const DELETE_BUSINESS_REQUEST = "DELETE_BUSINESS_REQUEST";
export const DELETE_BUSINESS_SUCCESS = "DELETE_BUSINESS_SUCCESS";
export const DELETE_BUSINESS_FAIL = "DELETE_BUSINESS_FAIL";
export const DELETE_BUSINESS_RESET = "DELETE_BUSINESS_RESET";
